### ISSUE TITLE
Upgrade to final release LaxarJS 2.0.0 and publish the demo

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/finder-demo#19]
- [x] Add laxar-developer-widget (npm package)
- [x] Use final releases of LaxarJS packages
- [x] Update style-loader (https://github.com/LaxarJS/shop-demo/issues/58)
- [x] Remove LaxarJS configuration `tooling` (init.js)

**Comment by jonaswjs** [comment]
Wating for https://github.com/LaxarJS/laxar-developer-tools-widget/issues/65

**Comment by x1B** [comment]
Fixed on `master` (`v2.0.0`).
